# -*- coding: utf-8 -*-
"""utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qhg1SbfoOlj_sML-SgvMYpoe4jYb_LVp
"""

import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin

class ObjectToFloatTransformer(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.encoders = {}
        self.columns_to_encode = []

    def fit(self, X, y=None):
        self.columns_to_encode = [col for col in X.columns if X[col].dtype == "object"]
        for col in self.columns_to_encode:
            le = LabelEncoder()
            le.fit(X[col])
            self.encoders[col] = le

        return self

    def transform(self, X):
        X_transformed = X.copy()
        for col in self.columns_to_encode:
            if col in X_transformed.columns and col in self.encoders:
                X_transformed[col] = self.encoders[col].transform(X_transformed[col])
                X_transformed[col] = X_transformed[col].astype('float64')
            else:
                pass
        return X_transformed


df_copy_for_encoding = df.copy()
object_transformer = ObjectToFloatTransformer()
df_encoded_class_version = object_transformer.fit_transform(df_copy_for_encoding)

print("\n DF original info:")
df.info()
print("\n DF transformado info:")
df_encoded_class_version.info()
print("\n Head DF transformada:")
print(df_encoded_class_version.head())